services:
  admin:
    image: postgres:15.4
    container_name: ec-db
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ec-volume:/data/db

volumes:
  ec-volume:

